#-------------------------------
# Site Settings
title: GPMH Lab
logo: /images/misc/GPMHlogo.png 
logo_dark: /images/misc/GPMHlogo_dark.png
logo_footer: /images/misc/qut3.png
description: Genomics, Performance and Mental Health Laboratory

#-------------------------------
# Author Global Settings
author:
  author__name: Genomics, Performance and Mental Health Lab
  author__bio: Queensland University of Technology, Australia
  author__avatar: '/images/misc/GPMHlogo_words.png'


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Research'
      url: '/research/'
    - title: 'Publications'
      url: '/publications/'
    - title: 'Resources'
      url: '/resources/'
    - title: 'People'
      submenu:
      - url: '/members/'
        title: 'Members'
      - url: '/alumni/'
        title: 'Alumni'
      - url: '/interns/'
        title: 'Interns'
      - url: '/open-positions/'
        title: 'Join us'


#-------------------------------
# Hero Settings
hero:
  hero__title: Genomics, Performance and Mental Health Lab
  hero__description: We are a multidisciplinary team working to advance technologies and systems-based biological approaches across genomics, human performance, and mental health. We develop and apply technologies to better measure, analyse, and interpret complex biological and behavioural data. By systems-based biological approaches, we mean studying how genes, molecules, physiology, behaviour, and environment interact as connected parts of human health and performance.

#-------------------------------
# Blog Settings
blog:
  blog__title: Projects


#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Activities
  tag__name: Activities


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__input__text: Your Email Address...
  mailchimp__button__text: Subscribe
  mailchimp__background__image: "/images/110.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Research'
      url: '/research/'
    - title: 'People'
      url: '/members/'
    - title: 'Contact'
      url: '/contact/'


# Social Links
social:
# - {color: "#000000", name: QUT, link: "https://www.qut.edu.au/about/our-people/academic-profiles/divya.mehta", icon_image: https://www.qut.edu.au/about/our-people/academic-profiles/divya.mehta}
# - {color: "#1185FE", name: Bluesky, link: "https://bsky.app/profile/niranjantw.bsky.social", icon_image: https://cdn.simpleicons.org/bluesky/white}
# - {color: "#181717", name: GitHub, link: "https://github.com/CSB5", icon_image: https://cdn.simpleicons.org/github/white}




# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: ruizpint@qut.edu.au # Add your email for contant form

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: G-BY80H59N0P